Update requirements.txt
Since JSON is Module i don't need to install it using pip but we need BeautifulSoup4 for this >>

Traceback (most recent call last):
  File "/home/kali/spyhunt/spyhunt.py", line 5, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'